
    
    
    
    
    
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//      Generated: Sun, 15 Jan 2023 23:38:58 GMT
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Newtonsoft.Json;
namespace WikiPageApp.Model
{
	public class WikiPage : IEntity
	{
		public WikiPage() {
			WikiPageUpdatedTimestampUTC = DateTime.UtcNow;
			WikiPageIsSoftDeleted = false;
		}

		[Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
		public Guid WikiPageID { get; set; } = Guid.NewGuid();
		
		//Definition Properties
		
[Column(TypeName ="int")] [Required] 
		public int WikiPageIDint { get; set; }
		 
		[Column(TypeName = "bit")] 
		public bool WikiPageIsSoftDeleted { get; set; }
		public DateTime WikiPageUpdatedTimestampUTC { get; set; }
		public Guid WikiPageUpdatedByResourceID { get; set; }
 
	}
}