
    
    
    
    
    
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//      Generated: Sun, 15 Jan 2023 23:38:58 GMT
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Newtonsoft.Json;
namespace WikiPageApp.Model
{
	public class WikiPageUpdate : IEntity
	{
		public WikiPageUpdate() {
			WikiPageUpdateUpdatedTimestampUTC = DateTime.UtcNow;
			WikiPageUpdateIsSoftDeleted = false;
		}

		[Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
		public Guid WikiPageUpdateID { get; set; } = Guid.NewGuid();
		
		//Definition Properties
		

		public Guid WikiPageID { get; set; }
		
[Column(TypeName="varchar(MAX)")]  [Required] 
		public string WikiPageTitleMAX { get; set; }
		
[Column(TypeName="datetime")] [Required] 
		public DateTime WikiPageUpdateInjestDatetime { get; set; }
		
[Column(TypeName ="int")] [Required] 
		public int WikiPageUpdateInjestOrderNum { get; set; }
		
[Column(TypeName="varchar(MAX)")]  [Required] 
		public string WikiPageUpdateJsonMAX { get; set; }
		
[Column(TypeName="datetime")] [Required] 
		public DateTime WikiPageUpdateTimestamp { get; set; }
		
[Column(TypeName ="int")] [Required] 
		public int WikiPageUpdateContributorIDInt { get; set; }
		 
		[Column(TypeName = "bit")] 
		public bool WikiPageUpdateIsSoftDeleted { get; set; }
		public DateTime WikiPageUpdateUpdatedTimestampUTC { get; set; }
		public Guid WikiPageUpdateUpdatedByResourceID { get; set; }
 
	}
}