
    
    
    
    
    
    
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//      Generated: Sun, 15 Jan 2023 23:38:58 GMT
// </auto-generated>
// ------------------------------------------------------------------------------

#nullable disable
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.OpenApi.Models;
using System.Threading.Tasks;
using WikiPageApp.Data;
using WikiPageApp.ApiCore.Routes;
namespace WikiPageApp.AwsLambdas.Controllers.WikiPage
{
    public partial class WikiPageController
    {        
        [HttpPost]        
        //[Route("WikiPage")]
        [Route(WikiPageRoutes.SaveSingle)]
        public async Task<IActionResult>SaveSingle([FromBody] Model.WikiPage wikiPage)
        {
            var existing = await _context.WikiPage.FindAsync(wikiPage.WikiPageID);

            if (existing == null) _context.WikiPage.Add(wikiPage);
            else
            {
                _context.WikiPage.Remove(existing);
                _context.WikiPage.Add(wikiPage);
            }

            await _context.SaveChangesAsync();
            return new OkObjectResult(wikiPage);
        }

    }
}