
    
    
    
    
    
    
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//      Generated: Sun, 15 Jan 2023 23:38:58 GMT
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WikiPageApp.ApiCore.Routes
{
    public static partial class WikiPageUpdateRoutes
    {
        public const string Root = "api/";
        public const string GetMany = Root + "WikiPageUpdates";
        public const string GetManyWithLinq = Root + "GetWikiPageUpdateManyWithLinq";
        public const string GetManyWithOData = Root + "GetWikiPageUpdateManyWithOData";
        public const string GetSingleByID = Root + "WikiPageUpdate/{id}";
        public const string SaveMany = Root + "WikiPageUpdates";
        public const string SaveSingle = Root + "WikiPageUpdate";
    }
}