// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//      Generated: Sun, 15 Jan 2023 23:38:58 GMT
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;

namespace WikiPageApp.Proto.Server.Services
{
    public interface IProtoServerServiceRegistrar
    {
        public void MapGrpcService<TService>()
            where TService : class;
    }
}
