// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//      Generated: Sun, 15 Jan 2023 23:38:58 GMT
// </auto-generated>
// ------------------------------------------------------------------------------
using WikiPageApp.Proto.Server.Services;
using System;
using System.Collections.Generic;
using System.Text;

namespace WikiPageApp.Proto.Server.Services
{
    public static class RegisterProtoServerServiceCommand
    {
        public static void Execute(IProtoServerServiceRegistrar registrar)
        {
            
                registrar.MapGrpcService<WikiPageServerService>();
            
                registrar.MapGrpcService<WikiPageUpdateServerService>();
            
                registrar.MapGrpcService<WikiPageUpdateSentServerService>();
                    }
    }
}
