
    
    
    
    
    
    
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//      Generated: Sun, 15 Jan 2023 23:38:58 GMT
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable disable
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.OpenApi.Models;
using WikiPageApp.ApiCore.Routes;

namespace WikiPageApp.WebApi.Controllers.WikiPageUpdateSent
{
    public partial class WikiPageUpdateSentController
    {
        // GET: WikiPageUpdateSent
        [HttpGet]
        //[Route("WikiPageUpdateSent/{id}")]
        [Route(WikiPageUpdateSentRoutes.GetSingleByID)]
        public async Task<IActionResult> GetSingleByID(Guid id)
        {
            var obj = await _context.WikiPageUpdateSent.FirstOrDefaultAsync(m => m.WikiPageUpdateSentID == id);
            return new OkObjectResult(obj);
        }

    }
}