
    
    
    
    
    
    
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//      Generated: Sun, 15 Jan 2023 23:38:58 GMT
// </auto-generated>
// ------------------------------------------------------------------------------
 
#nullable disable
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.OpenApi.Models;
using WikiPageApp.Data;
using WikiPageApp.ApiCore.Routes;

namespace WikiPageApp.WebApi.Controllers.WikiPageUpdateSent
{
    public partial class WikiPageUpdateSentController
    {
        [HttpPost]        
        //[Route("WikiPageUpdateSents")]
        [Route(WikiPageUpdateSentRoutes.SaveMany)]
        public async Task<IActionResult> SaveMany([FromBody] List<Model.WikiPageUpdateSent> objList)
        {
            List<Model.WikiPageUpdateSent> savedList = new List<Model.WikiPageUpdateSent>();
            foreach (var obj in objList)
            {
                try
                {
                    var existing = await _context.WikiPageUpdateSent.FindAsync(obj.WikiPageUpdateSentID);

                    if (existing == null) _context.WikiPageUpdateSent.Add(obj);
                    else
                    {
                        _context.WikiPageUpdateSent.Remove(existing);
                        _context.WikiPageUpdateSent.Add(obj);
                    }
                    await _context.SaveChangesAsync();
                    savedList.Add(obj);
                }
                catch (Exception ex)
                {
                    continue;
                }
            }
            return new OkObjectResult(objList);
        }

    }
}