
    
    
    
    
    
    
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//      Generated: Sun, 15 Jan 2023 23:38:58 GMT
// </auto-generated>
// ------------------------------------------------------------------------------
 
#nullable disable
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.OpenApi.Models;
using WikiPageApp.Data;
using WikiPageApp.ApiCore.Routes;

namespace WikiPageApp.WebApi.Controllers.WikiPage
{
    public partial class WikiPageController
    {
        [HttpPost]        
        //[Route("WikiPages")]
        [Route(WikiPageRoutes.SaveMany)]
        public async Task<IActionResult> SaveMany([FromBody] List<Model.WikiPage> objList)
        {
            List<Model.WikiPage> savedList = new List<Model.WikiPage>();
            foreach (var obj in objList)
            {
                try
                {
                    var existing = await _context.WikiPage.FindAsync(obj.WikiPageID);

                    if (existing == null) _context.WikiPage.Add(obj);
                    else
                    {
                        _context.WikiPage.Remove(existing);
                        _context.WikiPage.Add(obj);
                    }
                    await _context.SaveChangesAsync();
                    savedList.Add(obj);
                }
                catch (Exception ex)
                {
                    continue;
                }
            }
            return new OkObjectResult(objList);
        }

    }
}