// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//      Generated: Sun, 15 Jan 2023 23:38:58 GMT
// </auto-generated>
// ------------------------------------------------------------------------------
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;
using System.Collections.Generic;
using System.Text;
using WikiPageApp.Model;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore.ChangeTracking;

namespace WikiPageApp.Data;

public class WikiPageUpdateSentDataContext : DbContext
{
    private string _connectionString;
    private string _EFProvider;

    public WikiPageUpdateSentDataContext(string connectionString, string EFProvider)
    {
        _connectionString = connectionString;
        _EFProvider = EFProvider;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (optionsBuilder.IsConfigured)
        {
            return;
        }

        optionsBuilder.SetProvider(_EFProvider, _connectionString);
    }

    public DbSet<WikiPageUpdateSent> WikiPageUpdateSent { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<WikiPageUpdateSent>(entity =>
        {
            entity.ToContainer(nameof(WikiPageUpdateSent)).HasNoDiscriminator()
                .HasKey(x => x.WikiPageUpdateSentID);

            entity.HasPartitionKey(x => x.WikiPageUpdateID);
        });
    }
}
